In [1]:
import pandas as pd

In [2]:
import sqlite3

In [4]:
pd.read_sql('SELECT Sex, AVG(Survived)' FROM titanic GROUP BY Sex, conn)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (535625344.py, line 1)

In [5]:
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(url)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [8]:
pd.read_sql('SELECT Sex, AVG(Survived)  FROM titanic GROUP BY Sex', conn)

NameError: name 'conn' is not defined

In [11]:
conn = sqlite3.connect('test.db')
import sqlite3
conn = sqlite3.connect('test.db')

In [12]:
df.to_sql('titanic', conn, if_exists='replace', index=False)

891

In [13]:
df.to_sql('titanic', conn, if_exists='replace', index=False)

891

In [14]:
pd.read_sql('SELECT Sex, AVG(Survived) FROM titanic GROUP BY sex', conn)

      Sex  AVG(Survived)
0  female       0.742038
1    male       0.188908